DROP DATABASE IF EXISTS DB_UNICHAR;
CREATE DATABASE DB_UNICHAR;
USE DB_UNICHAR;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (	
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME CHAR(20) NOT NULL,
  SURNAME CHAR(20) NOT NULL,
  USERNAME CHAR(20) NOT NULL,
  PASSWORD CHAR(20) NOT NULL,
  ROLE CHAR(20) NOT NULL
);


INSERT INTO USERS VALUES (1,"Dylan","Dog","DD6","groucho", "user");
INSERT INTO USERS VALUES (2,"Eva","Kant","EK67","walter", "admin");
INSERT INTO USERS VALUES (3, "Levi", "Ackermann", "LA555", "mikasa", "manager");

DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PRICE FLOAT NOT NULL,
    DESCR CHAR(255),
    TITLE CHAR(30),
    DEVELOPER CHAR(30),
    IMG_PATH_ONE CHAR(30),
    IMG_PATH_TWO CHAR(30),
    IMG_PATH_THREE CHAR(30)
    );

INSERT INTO PRODUCTS VALUES (1, 23, "TACTICAL ESPIONAGE ACTION", "METAL GEAR SOLID", "KONAMI", "1.jpg", "", "");
INSERT INTO PRODUCTS VALUES (2, 43, "POST APOCALIPTIC ADVENTURE", "FALLOUT", "BLACK ISLE", "2.jpg", "", "");
INSERT INTO PRODUCTS VALUES (3, 42, "POST APOCALIPTIC ADVENTURE", "FALLOUT 2", "BLACK ISLE", "3.jpg", "", "");
INSERT INTO PRODUCTS VALUES (4, 21, "POST APOCALIPTIC ADVENTURE", "FALLOUT NEW VEGAS", "OBSIDIAN", "4.jpg", "", "");
INSERT INTO PRODUCTS VALUES (5, 2, "THE ELDER SCROLLS", "SKYRIM", "BETHESDA", "5.jpg", "", "");
INSERT INTO PRODUCTS VALUES (6, 39, "ASYMMETRICAL HORROR", "EVIL DEAD: THE GAME", "SABER INTERACTIVE", "2.jpg", "", "");
INSERT INTO PRODUCTS VALUES (7, 15, "EPIC SMALL ADVENTURE", "HOLLOW KNIGHT", "TEAM CHERRY", "7.jpg", "", "");
INSERT INTO PRODUCTS VALUES (8, 67, "CATCH 'EM ALL!", "POKEMON SWORD", "GAME FREAK", "8.jpg", "", "");
INSERT INTO PRODUCTS VALUES (9, 67, "CATCH 'EM ALL!", "POKEMON SHIELD", "GAME FREAK", "9.jpg", "", "");
INSERT INTO PRODUCTS VALUES (10, 99, "SURVIVAL HORROR STORY", "SILENT HILL 3", "KONAMI", "10.jpg", "", "");
INSERT INTO PRODUCTS VALUES (11, 99, "SURVIVAL HORROR STORY", "SILENT HILL 2", "KONAMI", "11.jpg", "", "");

SELECT * FROM PRODUCTS LIMIT 1;