DROP DATABASE IF EXISTS DB_UNICHAR;
CREATE DATABASE DB_UNICHAR;
USE DB_UNICHAR;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (	
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME CHAR(20) NOT NULL,
  SURNAME CHAR(20) NOT NULL,
  USERNAME CHAR(20) NOT NULL,
  PASSWORD CHAR(20) NOT NULL,
  ROLE CHAR(20) NOT NULL,
  EMAIL CHAR(35) NOT NULL
);


INSERT INTO USERS VALUES (1,"DYLAN","DOG","DD6","GROUCHO", "USER", "LELLO@FAST.IT");
INSERT INTO USERS VALUES (2,"EVA","KANT","EK67","WALTER", "ADMIN", "BIAGIO@FAST.IT");
INSERT INTO USERS VALUES (3, "LEVI", "ACKERMANN", "LA555", "MIKASA", "MANAGER", "ANDREA@FAST.IT");

DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PRICE FLOAT NOT NULL,
    DESCR CHAR(255),
    TITLE CHAR(30),
    DEVELOPER CHAR(30),
    IMG_PATH_ONE CHAR(30),
    IMG_PATH_TWO CHAR(30),
    IMG_PATH_THREE CHAR(30),
    STOCK INT,
    DISCOUNT_PERC FLOAT DEFAULT 0
    );

INSERT INTO PRODUCTS VALUES (1, 23, "TACTICAL ESPIONAGE ACTION", "METAL GEAR SOLID", "KONAMI", "1.JPG", "", "", 12, 15);
INSERT INTO PRODUCTS VALUES (2, 43, "POST APOCALIPTIC ADVENTURE", "FALLOUT", "BLACK ISLE", "2.JPG", "", "", 44, 0);
INSERT INTO PRODUCTS VALUES (3, 42, "POST APOCALIPTIC ADVENTURE", "FALLOUT 2", "BLACK ISLE", "3.JPG", "", "", 15, 0);
INSERT INTO PRODUCTS VALUES (4, 21, "POST APOCALIPTIC ADVENTURE", "FALLOUT NEW VEGAS", "OBSIDIAN", "4.JPG", "", "", 54, 75);
INSERT INTO PRODUCTS VALUES (5, 2, "THE ELDER SCROLLS", "SKYRIM", "BETHESDA", "5.JPG", "", "", 231, 0);
INSERT INTO PRODUCTS VALUES (6, 39, "ASYMMETRICAL HORROR", "EVIL DEAD: THE GAME", "SABER INTERACTIVE", "2.JPG", "", "", 44, 0);
INSERT INTO PRODUCTS VALUES (7, 15, "EPIC SMALL ADVENTURE", "HOLLOW KNIGHT", "TEAM CHERRY", "7.JPG", "", "", 76, 0);
INSERT INTO PRODUCTS VALUES (8, 67, "CATCH 'EM ALL!", "POKEMON SWORD", "GAME FREAK", "8.JPG", "", "", 54, 0);
INSERT INTO PRODUCTS VALUES (9, 67, "CATCH 'EM ALL!", "POKEMON SHIELD", "GAME FREAK", "9.JPG", "", "", 78, 0);
INSERT INTO PRODUCTS VALUES (10, 99, "SURVIVAL HORROR STORY", "SILENT HILL 3", "KONAMI", "10.JPG", "", "", 66, 0);
INSERT INTO PRODUCTS VALUES (11, 99, "SURVIVAL HORROR STORY", "SILENT HILL 2", "KONAMI", "11.JPG", "", "", 54, 0);

CREATE TABLE ORDERS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  MAIL CHAR(35)
);

INSERT INTO ORDERS VALUES (1, "biagio@fast.it");

CREATE TABLE ORDER_DETAILS (
  ID INT,
  PRICE FLOAT, 
  QUANTITY INT,
  PROD_ID INT,
  KEY_STATUS enum('NON VISUALIZZATA','VISUALIZZATA'),
  FOREIGN KEY (ID) REFERENCES ORDERS(ID)
);

INSERT INTO ORDER_DETAILS VALUES (1, 10, 3, 6, 1);
INSERT INTO ORDER_DETAILS VALUES (1, 15, 6, 9, 2);


SELECT * FROM PRODUCTS;